palpiteiro:
  outputs:
    default:
      dataset: palpiteiro
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us
      method: oauth
      priority: interactive
      threads: 4
      type: bigquery
  target: default
