palpiteiro:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: palpiteiro-dev
      dataset: palpiteiro
      threads: 4 
      location: us
      priority: interactive
    main:
      type: bigquery
      method: oauth
      project: palpiteiro-main
      dataset: palpiteiro
      threads: 4 
      location: us
      priority: interactive
  target: dev
