version: 2

models:
  - name: fct_scoring
    description: Cartola players scoring for each round
    columns:
      - name: player_id
        description: Player ID
        tests:
          - not_null
      - name: season
        description: Season
        tests:
          - not_null
      - name: round
        description: Round
        tests:
          - not_null
      - name: club
        description: Club
        tests:
          - not_null
      - name: position
        description: Position
        tests:
          - not_null
          - accepted_values:
              values:
                - goalkeeper
                - fullback
                - defender
                - midfielder
                - forward
                - coach
      - name: position_id
        description: Position ID
        tests:
          - not_null
          - accepted_values:
              values:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
              quote: false
      - name: status
        description: Status for the match
        tests:
          - accepted_values:
              values:
                - doubt
                - suspended
                - injured
                - "null"
                - expected
      - name: total_points
        description: Points scored the player in the match using most recent rules.
        tests:
          - not_null:
              config:
                  where: "played IS TRUE"
      - name: offensive_points
        description: Offensive points scored the player in the match using most recent rules.
        tests:
          - not_null:
              config:
                  where: "played IS TRUE"
      - name: defensive_points
        description: Defensive points scored the player in the match using most recent rules.
        tests:
          - not_null:
              config:
                  where: "played IS TRUE"
      - name: played
        description: Indicates if the player played in the match.
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
              quote: false
      - name: price
        description: Price
        tests:
          - not_null
      - name: variation
        description: Price variation
        tests:
          - not_null

  - name: fct_match
    description: Cartola matches
    columns:
      - name: season
        description: Season
        tests:
          - not_null
      - name: round
        description: Round
        tests:
          - not_null
      - name: timestamp
        description: UTC date
        tests:
          - not_null
      - name: valid
        description: Is valid for this Cartola round
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
      - name: club
        description: Club
        tests:
          - not_null
      - name: opponent
        description: Opponent
        tests:
          - not_null
      - name: home
        description: Home
        tests:
          - not_null
          - accepted_values:
              values: [true, false]
              quote: false

  - name: dim_player
    description: Cartola players
    columns:
      - name: player_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: slug
        description: Slug
        tests:
          - not_null
      - name: nickname
        description: Nickname
        tests:
          - not_null
      - name: short_nickname
        description: Nickname
        tests:
          - not_null
      - name: photo
        description: Photo