version: 2

models:
  - name: stg_atletas_scoring
    description: Cartola players scoring for each round
    columns:
      - name: play_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: player_id
        description: Player ID
        tests:
          - not_null
      - name: round
        description: League round
        tests:
          - not_null
      - name: season
        description: League season
        tests:
          - not_null
      - name: club
        description: Club
        tests:
          - not_null
      - name: position
        description: Position
        tests:
          - not_null
          - accepted_values:
              values:
                - goalkeeper
                - defender
                - fullback
                - midfielder
                - forward
                - coach
              quote: true
      - name: position_id
        description: Position ID
        tests:
          - not_null
          - accepted_values:
              values:
                - 1
                - 2
                - 3
                - 4
                - 5
                - 6
              quote: false
      - name: status
        description: Status for the match
        tests:
          - accepted_values:
              values:
                - doubt
                - suspended
                - injured
                - "null"
                - expected
              quote: true
      - name: points
        description: Scored by the player in the match
        tests:
        - not_null
      - name: price
        description: Price
        tests:
          - not_null
          - not_negative
      - name: variation
        description: Price variation
        tests:
          - not_null

  - name: stg_atletas_player
    description: Cartola players
    columns:
      - name: player_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: slug
        description: Slug
        tests:
          - not_null
      - name: nickname
        description: Nickname
        tests:
          - not_null
      - name: short_nickname
        description: Nickname
        tests:
          - not_null
      - name: photo
        description: Photo

  - name: stg_partidas_match
    description: Cartola matches
    columns:
      - name: match_id
        description: Primary key
        tests:
          - not_null
          - unique
      - name: match_slug
        description: Match slug
        tests:
          - not_null
          - unique
      - name: season
        description: Season
        tests:
          - not_null
      - name: round
        description: Round
        tests:
          - not_null
      - name: timestamp
        description: UTC date
        tests:
          - not_null
      - name: valid
        description: Is valid for this Cartola round
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
      - name: home
        description: Home club
        tests:
          - not_null
      - name: away
        description: Away club
        tests:
          - not_null

  - name: stg_pontuados_scoring
    description: Cartola players scoring for each round
    columns:
      - name: play_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: player_id
        description: Player ID
        tests:
          - not_null
      - name: round
        description: League round
        tests:
          - not_null
      - name: season
        description: League season
        tests:
          - not_null
      - name: club
        description: Club
        tests:
          - not_null
      - name: position
        description: Position
        tests:
          - not_null
          - accepted_values:
              values:
                - goalkeeper
                - defender
                - fullback
                - midfielder
                - forward
                - coach
              quote: true
      - name: played
        description: Participated in this match
        tests:
          - not_null
          - accepted_values:
              values: [false, true]
              quote: false
      - name: points
        description: Points scored by the player in the match
        tests:
          - not_null
      - name: goal
        description: Goals in this match
        tests:
          - not_null
      - name: assist
        description: Assists in this match
        tests:
          - not_null
      - name: yellow_card
        description: Yellow cards in this match
        tests:
          - not_null
      - name: red_card
        description: Red cards in this match
        tests:
          - not_null
      - name: missed_shoot
        description: Missed shoots in this match
        tests:
          - not_null
      - name: on_post_shoot
        description: On post shoots in this match
        tests:
          - not_null
      - name: saved_shoot
        description: Saved shoots in this match
        tests:
          - not_null
      - name: received_foul
        description: Received fouls in this match
        tests:
          - not_null
      - name: received_penalty
        description: Received fouls in this match
        tests:
          - not_null
      - name: missed_penalty
        description: Missed penalty kick in this match
        tests:
          - not_null
      - name: outside
        description: Outsides in this match in this match
        tests:
          - not_null
      - name: missed_pass
        description: Missed passes in this match
        tests:
          - not_null
      - name: tackle
        description: Successful tackles in this match
        tests:
          - not_null
      - name: foul
        description: Committed fouls in this match
        tests:
          - not_null
      - name: penalty
        description: Committed penalty in this match
        tests:
          - not_null
      - name: own_goal
        description: Own goals in this match
        tests:
          - not_null
      - name: allowed_goal
        description: Allowed goals in this match
        tests:
          - not_null
      - name: no_goal
        description: Games without goals in this match
        tests:
          - not_null
      - name: save
        description: Saves in this match
        tests:
          - not_null
      - name: penalty_save
        description: Penalty save in this match
        tests:
          - not_null

  - name: stg_destaque_popular.sql
    description: 20 most popular players on Cartola for each round.
    columns:
      - name: play_id
        description: Play ID
        tests:
          - unique
          - not_null
      - name: player_id
        description: Player ID
        tests:
          - not_null
      - name: season
        description: Season
        tests:
          - not_null
      - name: round
        description: Round
        tests:
          - not_null
      - name: drafts
        description: Number of users that drafted this player to their team
        tests:
          - not_null
