version: 2

models:
  - name: fct_h2h
    description: Brasileirão betting odds
    tests:
      - unique:
          column_name: season || '-' || date(timestamp) || '-' || club
    columns:
      - name: season
        description: Season
        tests:
          - not_null
      - name: timestamp
        description: Match timestamp
        tests:
          - not_null
      - name: club
        description: Club
        tests:
          - not_null
      - name: opponent
        description: Opponent
        tests:
          - not_null
      - name: avg_club
        description: Club average odds
      - name: avg_opponent
        description: Opponent average odds
      - name: avg_draw
        description: Draw average odds