version: 2

models:
  - name: stg_spi_match
    description: Brasileirão Fivethirtyeight Soccer Power Index
    columns:
      - name: season
        description: Season
        tests:
          - not_null
      - name: date
        description: Date
        tests:
          - not_null
      - name: league_id
        description: League ID
        tests:
          - not_null
          - accepted_values:
              values: [2105]
              quote: false
      - name: home
        description: Home club
        tests:
          - not_null
      - name: away
        description: Away club
        tests:
          - not_null
      - name: spi_home
        description: Home club soccer power index
        tests:
          - not_null
      - name: spi_away
        description: Away club soccer power index
        tests:
          - not_null
      - name: prob_home
        description: Home club win probability
        tests:
          - not_null
      - name: prob_away
        description: Away club win probability
        tests:
          - not_null
      - name: prob_tie
        description: Tie probability
        tests:
          - not_null
      - name: importance_home
        description: Home club match importance
      - name: importance_away
        description: Away club match importance
      - name: proj_score_home
        description: Home club projected score
        tests:
          - not_null
      - name: proj_score_away
        description: Away club projected score
        tests:
          - not_null
