name: Build

on:
  push:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  dbt:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Build
        run: dbt build --target dev

      - name: Generate Docs
        if: ${{ github.REF_NAME == 'main' }}
        run: |
          dbt docs generate
          mkdir docs
          cp target/catalog.json __docs__/catalog.json
          cp target/manifest.json __docs__/manifest.json
          cp target/run_results.json __docs__/run_results.json
          cp target/index.html __docs__/index.html

      - name: Uppload Docs
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.REF_NAME == 'main' }}
        with:
          path: __docs__

      - name: Deploy Docs
        uses: actions/deploy-pages@v4
        if: ${{ github.REF_NAME == 'main' }}
