name: Build

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  dbt:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/1022055560421/locations/global/workloadIdentityPools/github-palpiteiro-data/providers/github
          service_account: github-palpiteiro-data@palpiteiro-dev.iam.gserviceaccount.com

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt
          dbt deps

      - name: Build
        run: dbt build --target dev

      - name: Generate Docs
        if: ${{ github.REF_NAME == 'main' }}
        run: |
          dbt docs generate
          mkdir docs
          cp target/catalog.json __docs__/catalog.json
          cp target/manifest.json __docs__/manifest.json
          cp target/run_results.json __docs__/run_results.json
          cp target/index.html __docs__/index.html

      - name: Uppload Docs
        uses: actions/upload-pages-artifact@v3
        if: ${{ github.REF_NAME == 'main' }}
        with:
          path: __docs__

      - name: Deploy Docs
        uses: actions/deploy-pages@v4
        if: ${{ github.REF_NAME == 'main' }}