name: Build

on:
  push:
    branches:
      - main
      - dev

jobs:
  dbt:
    runs-on: ubuntu-latest
    environment: ${{ github.REF_NAME }}

    env:
      DBT_PROFILES_DIR: "."

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: pprojects/1022055560421/locations/global/workloadIdentityPools/github-palpiteiro-data/providers/github
          service_account: github-palpiteiro-data@palpiteiro-dev.iam.gserviceaccount.com

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: pip install -r requirements

      - name: Build
        run: dbt build

      - name: Generate Docs
        if: ${{ github.REF_NAME == 'main' }}
        run: |
          dbt docs generate
          mkdir docs
          cp target/catalog.json docs/catalog.json
          cp target/manifest.json docs/manifest.json
          cp target/run_results.json docs/run_results.json
          cp target/index.html docs/index.html

      - name: Deploy Github Pages
        if: ${{ github.REF_NAME == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: github-pages
          folder: docs
