name: dbt
on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: "."
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Authenticate GCP
        uses: "google-github-actions/auth@v0.7.1"
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Requirements
        run: pip install dbt-bigquery
      - name: Build
        run: dbt build
      - name: Generate Docs
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          dbt docs generate
          mkdir docs
          cp dbt/target/catalog.json docs/catalog.json
          cp dbt/target/manifest.json docs/manifest.json
          cp dbt/target/run_results.json docs/run_results.json
          cp dbt/target/index.html docs/index.html
      - name: Deploy Github Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: github-pages
          folder: docs
