name: Linting

on:
  pull_request:
    branches:
      - main
  
jobs:
  linting:
    runs-on: ubuntu-latest
    environment: ${{ github.BASE_REF }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: pip install -r requirements.txt -r requirements-lint.txt

      - name: Lint
        run: sqlfluff lint

