name: Freshness

on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:

jobs:
  freshness:
    strategy:
      fail-fast: false
      matrix:
        env:
          - main
          - dev
          
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.env }}

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEYFILE }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Freshness
        run: dbt source freshness

   steps: