version: 2

sources:
  - name: cartola
    database: matheusccouto
    freshness:
      error_after:
        count: 1
        period: day
    loaded_at_field: loaded_at
    tables:
      - name: atletas
      - name: clubes
      - name: destaques
      - name: esquemas
      - name: partidas
      - name: pontuados
      - name: posicoes
      - name: status
