version: 2

sources:
  - name: cartola
    freshness:
      error_after:
        count: 1
        period: day
    loaded_at_field: loaded_at
    tables:
      - name: atletas
      - name: partidas
      - name: pontuados
      - name: selecao
      - name: destaques

  - name: fivethirtyeight
    freshness:
      error_after:
        count: 1
        period: day
    loaded_at_field: loaded_at
    tables:
      - name: spi

  - name: odds
    freshness:
      error_after:
        count: 1
        period: day
    loaded_at_field: loaded_at
    tables:
      - name: brasileirao

  - name: transfermarkt
    freshness:
      error_after:
        count: 7
        period: day
    loaded_at_field: loaded_at
    tables:
      - name: appearances
      - name: clubs
      - name: competitions
      - name: games
      - name: player_valuations
      - name: players
